Fix inline grails build of transmartApp
Unfortunately, the test-scoped dependency on http-builder overrides the
one for the same artifact in transmartApp when transmart-rest-api is
inline. I couldn't avoid this behavior, even with exported = false, so I
had to exclude the groovy dependency here on transmart-rest-api as well
(otherwise the old groovy-1.8.8 dependency gives us a nice

java.lang.IncompatibleClassChangeError: the number of constructors
during runtime and compile time for
org.grails.plugin.resource.mapper.MapperPhase do not match. Expected -1
but got 1

at runtime. This doesn't really fix the rest-api dependency overriding
the transmartApp depdency (very likely a Grails bug), we still get
http-builder 0.6 (transmart-rest-api) instead of 0.5.1 (transmartApp) in
the final WAR.