Revert "missing include - TAR_COMMAND was undefined"
This reverts commit 5f8f791b7bb9ea992c652d2171aa9a19903bd274.

The env Makefile is used to generate the vars file, but by including
makefile.inc, a dependency on these variables is introduced.

The undefined reference to TAR_COMMAND still has to be resolved, though.